volumes:
  pg_data:

services:
  db:
    image: postgres:16
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ~/page_analyzer_flask/database.sql:/docker-entrypoint-initdb.d/database.sql

  flask:
    build: .
    env_file: .env
    depends_on:
      - db
    ports:
      - 5001:5001
